spring:
  datasource:
    url: jdbc:h2:file:/var/lib/h2/timer_project_db # Usando H2 em disco para produção
    username: prod_user
    password: prod_password
  jpa:
    hibernate:
      ddl-auto: validate # Validação do esquema do banco de dados em produção
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  security:
    basic:
      enabled: true
    user:
      name: admin
      password: secure_password_prod # Defina senhas diferentes para produção
      roles: USER
