spring:
  datasource:
    url: jdbc:h2:mem:timer_project_db # Base de dados em memória para desenvolvimento
    username: dev_user
    password: dev_password
  jpa:
    hibernate:
      ddl-auto: update # Opção de auto-criação de tabelas no banco de dados
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  security:
    basic:
      enabled: true
    user:
      name: admin
      password: password123
      roles: USER
