spring:
  datasource:
    url: jdbc:postgresql://turntable.proxy.rlwy.net:30135/railway?ssl=true&sslmode=require
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  server:
    port: ${PORT:8080}
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      enabled: true